---
- hosts: pibox
  become: true
  tasks:
    - include_tasks: deploy/ssh.yml
    - include_tasks: deploy/packages.yml
    - include_tasks: deploy/filesystem.yml
    - include_tasks: deploy/helpers.yml
    - include_tasks: deploy/supervisor.yml
