---
- name: make futel directory
  file:
    path: /opt/futel
    state: directory
- name: make source directory
  file:
    path: /opt/futel/src
    state: directory
- name: make var directory
  file:
    path: /opt/futel/var
    state: directory
- name: make mount directory
  file:
    path: /mnt/futel
    state: directory
# - name: mount flash drive
#   mount:
#     path: /mnt/futel
#     src: UUID=E722-DEBB
#     fstype: vfat
#     opts: defaults,auto,users,rw
#     state: mounted
