---
- name: make futel directory
  file:
    path: /opt/futel
    state: directory
- name: make source directory
  file:
    path: /opt/futel/src
    state: directory
- name: make var directory
  file:
    path: /opt/futel/var
    state: directory
- name: make mount directory
  file:
    path: /mnt/futel
    state: directory
# assumes that drive ends up at /dev/sda1
# this should be true for the first drive connected?
- name: mount usb flash drive
  mount:
    path: /mnt/futel
    src: /dev/sda1
    fstype: vfat
    opts: defaults,auto,users,rw
    state: mounted
