---
- name: copy audio assets
  copy:
    src: src/opt/futel/src/audio/
    dest: /opt/futel/src/audio/
- name: copy pd dir
  copy:
    src: src/opt/futel/src/pd/
    dest: /opt/futel/src/pd/
- name: copy hookswitch
  copy:
    src: src/opt/futel/src/hookswitch.py
    dest: /opt/futel/src/hookswitch.py
    owner: pi
    group: pi
- name: copy log
  copy:
    src: src/opt/futel/src/log.py
    dest: /opt/futel/src/log.py
    owner: pi
    group: pi
- name: copy tones
  copy:
    src: src/opt/futel/src/tones.py
    dest: /opt/futel/src/tones.py
    owner: pi
    group: pi
- name: copy keypad script
  copy:
    src: src/opt/futel/src/keypad.py
    dest: /opt/futel/src/keypad.py
    owner: pi
    group: pi
- name: copy audiofone script
  copy:
    src: src/opt/futel/src/audiofone.py
    dest: /opt/futel/src/audiofone.py
    owner: pi
    group: pi
- name: make script executable
  file:
    path: /opt/futel/src/audiofone.py
    mode: "u+x"
