---
- name: copy assets
  copy:
    src: src/opt/futel/src/audio/dialtone.wav
    dest: /opt/futel/src/audio/dialtone.wav
- name: copy pd dir
  copy:
    src: src/opt/futel/src/pd/
    dest: /opt/futel/src/pd/
- name: make pd start script runnable
  file:
    path: /opt/futel/src/pd/run-pd.sh
    mode: "u+x"
- name: copy hookswitch
  copy:
    src: src/opt/futel/src/hookswitch.py
    dest: /opt/futel/src/hookswitch.py
    owner: pi
    group: pi
- name: copy tones
  copy:
    src: src/opt/futel/src/tones.py
    dest: /opt/futel/src/tones.py
    owner: pi
    group: pi
- name: copy keypad
  copy:
    src: src/opt/futel/src/keypad.py
    dest: /opt/futel/src/keypad.py
    owner: pi
    group: pi
- name: copy audiofone
  copy:
    src: src/opt/futel/src/audiofone.py
    dest: /opt/futel/src/audiofone.py
    owner: pi
    group: pi
- name: make script executable
  file:
    path: /opt/futel/src/hookswitch.py
    mode: "u+x"
