---
# I have no clue what I'm doing
- name: copy pd supervisor config
  copy:
    src: src/etc/supervisor/conf.d/puredata.conf
    dest: /etc/supervisor/conf.d/puredata.conf
- name: (re)start supervisord
  ansible.builtin.service:
    name: supervisor
    state: restarted
