---
- name: copy supervisor config
  copy:
    src: src/etc/supervisor/conf.d/{{item}}
    dest: /etc/supervisor/conf.d
  with_items:
    - puredata.conf
    - audiofone.conf
- name: (re)start supervisord
  ansible.builtin.service:
    name: supervisor
    state: restarted
